In [7]:
with open("input.txt", "r") as file:
    text = file.read()

In [3]:
import sentencepiece as spm

In [8]:
# 1. Train a model directly from a raw text file.
# (No pre-tokenization or language-specific preprocessing required!)
spm.SentencePieceTrainer.train(
    input='input.txt', 
    model_prefix='m', 
    vocab_size=1000
)

# 2. Load the trained model.
sp = spm.SentencePieceProcessor(model_file='m.model')

# 3. Encode raw text into subword pieces (strings) or vocabulary IDs (integers).
#text = "I saw a girl with a telescope."
pieces = sp.encode(text, out_type=str)
ids = sp.encode(text, out_type=int)

print(f"Pieces: {pieces[:1000]}")
# Output: ['▁I', '▁saw', '▁a', '▁girl', '▁with', '▁a', '▁', 'te', 'le', 's', 'c', 'o', 'pe', '.']

print(f"IDs:    {ids[:1000]}")
# Output: [9, 459, 11, 939, 44, 11, 4, 142, 82, 8, 28, 21, 132, 6]

# 4. Decode IDs or pieces back into the original text.
# The reconstruction is completely lossless and reversible!
print(sp.decode(ids[:1000]))
# Output: "I saw a girl with a telescope."

print(sp.decode(pieces[:1000]))
# Output: "I saw a girl with a telescope."

Pieces: ['▁First', '▁Citizen', ':', '▁Be', 'for', 'e', '▁we', '▁pro', 'ce', 'ed', '▁any', '▁further', ',', '▁hear', '▁me', '▁speak', '.', '▁A', 'll', ':', '▁S', 'pe', 'a', 'k', ',', '▁speak', '.', '▁First', '▁Citizen', ':', '▁You', '▁are', '▁all', '▁re', 's', 'ol', 've', 'd', '▁rather', '▁to', '▁die', '▁than', '▁to', '▁f', 'am', 'ish', '?', '▁A', 'll', ':', '▁R', 'es', 'ol', 've', 'd', '.', '▁re', 's', 'ol', 've', 'd', '.', '▁First', '▁Citizen', ':', '▁First', ',', '▁you', '▁know', '▁C', 'a', 'i', 'u', 's', '▁Marcius', '▁is', '▁', 'ch', 'ie', 'f', '▁enemy', '▁to', '▁the', '▁people', '.', '▁A', 'll', ':', '▁We', '▁know', "'", 't', ',', '▁we', '▁know', "'", 't', '.', '▁First', '▁Citizen', ':', '▁Let', '▁us', '▁kill', '▁him', ',', '▁and', '▁we', "'", 'll', '▁have', '▁c', 'or', 'n', '▁at', '▁our', '▁own', '▁pr', 'ice', '.', '▁I', 's', "'", 't', '▁a', '▁', 'ver', 'd', 'ic', 't', '?', '▁A', 'll', ':', '▁No', '▁more', '▁talk', 'ing', '▁on', "'", 't', ';', '▁let', '▁it', '▁be', '▁done', ':', '

In [ ]:
# print("Length of text:", len(text))

Lenth of text: 1115394


In [ ]:
# print(text[:1000])  # Print the first 500 characters of the text

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [ ]:
# chars=sorted(list(set(text)))
# vocab_size=len(chars)
# print(''.join(chars))
# print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [ ]:
# stoi={ch:i for i, ch in enumerate(chars)}
# itos={i:ch for i, ch in enumerate(chars)}
# encode=lambda s: [stoi[c] for c in s]
# decode=lambda l: ''.join([itos[i] for i in l])

# print(encode("hii there"))
# print(decode(encode("hii there")))

#the most simplest tokenizer--> should look into tokenizer of google

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [13]:
%pip install torch torchvision torchaudio

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# import torch
# data = torch.tensor(encode(text), dtype=torch.long)
# print(data.shape, data.dtype)
# print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [ ]:
n=int(0.9*len(pieces))
train_data=pieces[:n]
val_data=pieces[n:]


In [16]:
block_size=8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [17]:
x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range(block_size):
    context=x[:t+1]
    target=y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [18]:
torch.manual_seed(1337)
batch_size=4
block_size=8

def get_batch(split):
    data=train_data if split=='train' else val_data
    ix=torch.randint(len(data)-block_size, (batch_size,))#torch.randint(range,numberofrandomintegers)-->range= 0 to range
    x=torch.stack([data[i:i+block_size]for i in ix])
    y=torch.stack([data[i+1:i+block_size+1]for i in ix])
    return x,y

xb,yb=get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('-----')

for b in range(batch_size):
    for t in range(block_size):
        context=xb[b,:t+1]
        target=yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
-----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 5

In [19]:
print(xb)#our input to the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [20]:
#cons of biagram model:
#It has no long-term memory. Because it only looks one step into the past, generated text quickly loses track of grammar, structure, and meaning, often resulting in repetitive or nonsensical gibberesqe.
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table=nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits=self.token_embedding_table(idx)
        
        if targets is None:
            loss=None
        else:
            B,T,C=logits.shape
            logits=logits.view(B*T,C)
            targets=targets.view(B*T)
            loss=F.cross_entropy(logits, targets)
        return logits,loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            #get the predictions
            logits, loss= self(idx)
            #focus only on last time step
            logits=logits[:,-1,:]#becomes B,C
            #apply softmax to get probabilities
            probs=F.softmax(logits, dim=1)#B,C
            #sample from the distribution
            idx_next=torch.multinomial(probs, num_samples=1)#B,1

            """If you always picked the highest score using something like torch.argmax(), 
            your language model would become completely deterministic. By using torch.multinomial,
            you introduce creativity and randomness. Even if one character is the favorite, 
            the model still has a small chance to pick an alternative, 
            making the generated text feel much more natural and varied!"""

            #append sampled index to the running sequence
            idx=torch.cat((idx,idx_next),dim=1)
        return idx


m=BigramLanguageModel(vocab_size)
logits,loss=m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx=torch.zeros((1,1),dtype=torch.long), max_new_tokens=100)[0].tolist() ))

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


In [21]:
optimizer=torch.optim.AdamW(m.parameters(),lr=1e-3)
#highly advanced, smart optimizer as compared to SGD which is looks at only the current gradient and has no memory of past steps

In [22]:
batch_size=32
for steps in range(10000):
    #sample a batch of data
    xb, yb=get_batch('train')

    #evaluate the loss
    logits, loss=m(xb,yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.382369041442871


In [23]:
print(decode(m.generate(idx=torch.zeros((1,1),dtype=torch.long), max_new_tokens=400)[0].tolist() ))


lso br. ave aviasurf my, yxMPZI ivee iuedrd whar ksth y h bora s be hese, woweee; the! KI 'de, ulseecherd d o blllando;LUCEO, oraingofof win!
RIfans picspeserer hee tha,
TOFonk? me ain ckntoty ded. bo'llll st ta d:
ELIS me hurf lal y, ma dus pe athouo
BEY:! Indy; by s afreanoo adicererupa anse tecorro llaus a!
OLeneerithesinthengove fal amas trr
TI ar I t, mes, n IUSt my w, fredeeyove
THek' merer,


In [ ]:
torch.manual_seed(1337)
B,T,C=4,8,32
x=torch.randn(B,T,C)

#single head performing self attention
head_size=16
key=nn.Linear(C, head_size, bias=False)
query=nn.Linear(C, head_size, bias=False)
value=nn.Linear(C,head_size, bias=False)
k=key(x) #B,T,16
q=key(x)#B,T,16
wei= q@k.transpose(-2,-1) #B,T,16 @ B,16,T= B,T,T
tril=torch.tril(torch.ones(T,T))
wei=wei.masked_fill(tril==0, float('-inf'))
wei=F.softmax(wei,dim=-1)
v=value(x)
out=wei @ v 
out.shape


torch.Size([4, 8, 16])